updated recovery installers

diff --git a/prebuilt/common/bin/fjtool b/prebuilt/common/bin/fjtool
--- a/prebuilt/common/bin/fjtool
+++ b/prebuilt/common/bin/fjtool
@@ -802,7 +802,7 @@ disabled() {
 echo --Feature disabled for now--
 }
 
-cwmrec() {
+cwmrec5() {
 FILE=cwmrec5.tgz
 MD5SUM=9c0a662a8f3abc56925bfb846e0b5d01
 URL="http://rootdev.org/i717/TU2/updates/cwmrec5.tgz"
@@ -850,7 +850,7 @@ if [ "$MK" = "1" ]; then
 fi
 }
 
-cwmtouch() {
+cwmrec6() {
 FILE=cwmtouch6.tgz
 MD5SUM=d54a2c1250ddc8f795aef00a8104180f
 URL="http://rootdev.org/i717/TU2/updates/cwmtouch6.tgz"
@@ -883,8 +883,56 @@ echo "Flashing Recovery"
 dd if=/sdcard/recovery.img of=/dev/block/mmcblk0p22
 echo "Cleaning up"
   cd - >/dev/null 2>&1
-  echo "Done! Please Reboot and Enjoy CWM Touch Recovery"
+  echo "Done! Please Reboot and Enjoy CWM Recovery 6.0.1.4"
   echo "Go give bhundven some thanks!"
+else
+  echo "Failed to Install CWM Touch Recovery"
+  echo "Try Again"
+  exit 1
+fi
+rm  /sdcard/recovery.img
+rm  /sdcard/download/rectmp/$FILE
+rm -R /sdcard/download/rectmp
+
+if [ "$MK" = "1" ]; then
+  rm -R /sdcard/download/rectmp 
+fi
+}
+
+cwmtouch() {
+FILE=cwmtouch5.tgz
+MD5SUM=d260c22aad6d2efcf764da695b3181c7
+URL="http://rootdev.org/i717/TU2/updates/cwmtouch5.tgz"
+if [ ! -d /sdcard/download/rectmp ]; then
+  MK=1
+  mkdir -p /sdcard/download/rectmp
+fi
+cd /sdcard/download/rectmp
+if [ -f "$FILE" ]; then
+MD5=`md5sum $FILE | awk '{ print $1 }'`
+  if [ "$MD5" = "$MD5SUM" ]; then
+     GOOD=1
+  fi
+fi
+if [ "$GOOD" != "1" ]; then 
+echo "Downloading Package Be Patient"
+rm  "$FILE"
+wget "$URL"
+  MD5=`md5sum $FILE | awk '{ print $1 }'`
+  if [ "$MD5" = "$MD5SUM" ]; then
+     GOOD=1
+  fi
+fi
+if [ "$GOOD" = "1" ]; then
+  cd /sdcard/download/rectmp
+echo "Extracting Package"
+  tar -xzf cwmtouch5.tgz
+echo "Flashing Recovery"
+  cp recovery.img /sdcard/recovery.img
+dd if=/sdcard/recovery.img of=/dev/block/mmcblk0p22
+echo "Cleaning up"
+  cd - >/dev/null 2>&1
+  echo "Done! Please Reboot and Enjoy CWM Touch Recovery"
 else
   echo "Failed to Install CWM Touch Recovery"
   echo "Try Again"
